export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const ADD_SINGLE_CART_ITEM = 'ADD_SINGLE_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REMOVE_SIGNLE_CART_ITEM = 'REMOVE_SIGNLE_CART_ITEM';
export const CART_EMPTY = 'CART_EMPTY';

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_SHIPPING_METHOD = 'CART_SAVE_SHIPPING_METHOD';

export const OPEN_CART_MODAL = 'OPEN_CART_MODAL';
