export const CUSTOMER_SIGNIN_REQUEST = 'CUSTOMER_SIGNIN_REQUEST';
export const CUSTOMER_SIGNIN_SUCCESS = 'CUSTOMER_SIGNIN_SUCCESS';
export const CUSTOMER_SIGNIN_FAIL = 'CUSTOMER_SIGNIN_FAIL';
export const CUSTOMER_SIGNOUT = 'CUSTOMER_SIGNOUT';

export const CUSTOMER_SIGNUP_REQUEST = 'CUSTOMER_SIGNUP_REQUEST';
export const CUSTOMER_SIGNUP_SUCCESS = 'CUSTOMER_SIGNUP_SUCCESS';
export const CUSTOMER_SIGNUP_FAIL = 'CUSTOMER_SIGNUP_FAIL';

export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST';
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESS';
export const CUSTOMER_DETAILS_FAIL = 'CUSTOMER_DETAILS_FAIL';

export const CUSTOMER_PROFILE_UPDATE_REQUEST = 'CUSTOMER_PROFILE_UPDATE_REQUEST';
export const CUSTOMER_PROFILE_UPDATE_SUCCESS = 'CUSTOMER_PROFILE_UPDATE_SUCCESS';
export const CUSTOMER_PROFILE_UPDATE_FAIL = 'CUSTOMER_PROFILE_UPDATE_FAIL';
export const CUSTOMER_PROFILE_UPDATE_RESET = 'CUSTOMER_PROFILE_UPDATE_RESET';
